### ISSUE TITLE
Any plan to upgrade to hyper 0.11 ?

### ISSUE THREAD

**Issue by fdubois1** [KeenS/www-authenticate#1]
I am already using hyper 0.11.  I just tried to include this crate, but I get issue with version : 

the trait bound `www_authenticate::WwwAuthenticate: hyper::header::Header` is not satisfied

but it should be satisfied.  I think the reason is because I'm using hyper 0.11 and this crate is based on 0.10.

Any plan to upgrade ?  Will take a look to do it, but I'm asking in case I'm missing something.
Thanks

**Comment by KeenS** [comment]
Sorry for late reply. I missed this issue. I'll release upgraded version in several days.

**Comment by KeenS** [comment]
@fdubois1 released new version which depends on hyper 0.11.0. https://crates.io/crates/www-authenticate/0.2.0

**Comment by fdubois1** [comment]
Thanks. I did what I needed but will take a look if I need more later.  Last week, we moved to hyper 0.12 and they removed all header type from it. But it exists hyperx to keep all types.

**Comment by KeenS** [comment]
I'm going to submit a PR to hyperx because we need.

**Comment by KeenS** [comment]
Closing this issue. for the state of integration of hyperx, see #2
